
SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
INSERT INTO department (id, createTime, updateTime, version, deptOrder, deptStatus, name, remark, serialNumber, parentDepartment_id) VALUES(1, '2010-03-26 00:41:50', NULL, 0, NULL, NULL, '组织机构', NULL, NULL, NULL);
INSERT INTO employee (id, createTime, updateTime, version, address, bianZhi, birthday, bz, contractMatureDate, contractRemark, contractSignDate, degree, disabilityIdcard, email, empNo, graduteDate, health, idcard, infoStatus, insurance, interest, jobChanges, mobile, msn, name, nation, nativeplace, participateDate, photo, physical, polity, qq, recognizor, remark, rewardsAndPunishiment, rpraddress, rprtel, rprtype, school, selfDesc, sex, speciality, tel, totp, weeding, workStatus, workTel, workTrain, zhiChen, zhiChenDate, department_id, user_id) VALUES(1, '2010-03-26 00:41:50', '2010-03-26 00:41:50', 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '管理员', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1);
INSERT INTO materialcategory (id, createTime, updateTime, version, name, note, serialNumber, visible, parentMaterialCategory_id) VALUES(1, '2010-03-26 00:41:50', NULL, 0, '物料分类', NULL, NULL, b'1', NULL);
INSERT INTO role (id, createTime, updateTime, version, name, remark, department_id) VALUES(1, '2010-03-26 00:41:49', '2010-03-26 00:41:50', 1, '管理员', NULL, NULL);
INSERT INTO role_systemresource (Role_id, systemResources_id) VALUES(1, 1);
INSERT INTO role_user (Role_id, users_id) VALUES(1, 1);
INSERT INTO systemmodule (id, createTime, updateTime, version, chineseName, name, shortName) VALUES(1, '2010-03-26 00:41:49', NULL, 0, '客户关系管理', 'ClientRelatiManagement', 'CRM');
INSERT INTO systemmodule (id, createTime, updateTime, version, chineseName, name, shortName) VALUES(2, '2010-03-26 00:41:49', NULL, 0, '业务销售管理', 'OperationsManagement', 'OM');
INSERT INTO systemmodule (id, createTime, updateTime, version, chineseName, name, shortName) VALUES(3, '2010-03-26 00:41:49', NULL, 0, '生产制造管理', 'ProductiveManagement', 'PM');
INSERT INTO systemmodule (id, createTime, updateTime, version, chineseName, name, shortName) VALUES(4, '2010-03-26 00:41:49', NULL, 0, '库存物料管理', 'WarehouseManagement', 'WM');
INSERT INTO systemmodule (id, createTime, updateTime, version, chineseName, name, shortName) VALUES(5, '2010-03-26 00:41:49', NULL, 0, '财务数据管理', 'FinancialManagement', 'FA');
INSERT INTO systemmodule (id, createTime, updateTime, version, chineseName, name, shortName) VALUES(6, '2010-03-26 00:41:49', NULL, 0, '人力资源管理', 'HumanResoursManage', 'HR');
INSERT INTO systemmodule (id, createTime, updateTime, version, chineseName, name, shortName) VALUES(7, '2010-03-26 00:41:49', NULL, 0, '资产设备管理', 'EquipmentManagement', 'EM');
INSERT INTO systemmodule (id, createTime, updateTime, version, chineseName, name, shortName) VALUES(8, '2010-03-26 00:41:49', NULL, 0, '办公自动化', 'OfficeManagement', 'EM');
INSERT INTO systemmodule (id, createTime, updateTime, version, chineseName, name, shortName) VALUES(9, '2010-03-26 00:41:49', NULL, 0, '系统管理', 'SystemManagement', 'SYS');
INSERT INTO systemresource (id, createTime, updateTime, version, content, name, remark, type, systemModule_id) VALUES(1, '2010-03-26 00:41:49', NULL, 0, 'ROLE_ADMIN', 'ROLE_ADMIN', NULL, 'ROLE', 9);
INSERT INTO user (id, createTime, updateTime, version, enabled, lastLoginIp, lastLoginTime, loginTimes, password, remark, url, userName, userType, employee_id) VALUES(1, '2010-03-26 00:41:50', '2010-03-26 00:41:50', 2, b'1', NULL, NULL, NULL, 'y109', NULL, NULL, 'y109', NULL, 1);
INSERT INTO user_role (User_id, roles_id) VALUES(1, 1);
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
