// default package
// Generated 2009-10-23 23:19:36 by Hibernate Tools 3.2.2.GA
import java.util.Date;

/*
 * AfElement generated by hbm2java
 */
public class AfElement implements java.io.Serializable {
	private Long afEId;
	private Long afId;
	private String EType;
	private Integer EAmount;
	private Double EPs;
	private String EMachine;
	private String EFormat;
	private String EColorFront;
	private String EColorBack;
	private Integer EColorFrontN;
	private Integer EColorBackN;
	private String EPaper;
	private String EPaperFrom;
	private String ESs;
	private Double EReam;
	private Double EOvers;
	private String EPlateType;
	private Integer EPlateAmount;
	private Date EPlanPm;
	private Date EPlanBp;
	private Date EPlanProof;
	private Date EPlanPress;
	private String EIdePm;
	private String EIdeBp;
	private String EIdeProof;
	private String EIdePress;
	private Date EComPm;
	private Date EComBp;
	private Date EComProof;
	private Date EComPress;
	private Integer EP;
	private Integer paperStatus;
	private String paperSupplyMan;
	private String paperGetMan;
	private Date paperSupplyTime;
	private Integer filmPlace;
	private Date pmstartTime;
	private String pmbindMan;
	private Integer pmfilmCheck;
	private String pmfilmStatus;
	private String pmsaiMethod;
	private String pmsaiMan;
	private Integer pmoldPs;
	private Integer pmnewPs;
	private Double pmsaiLong;
	private Double pmsaiMpa;
	private Date pmpushSampleTime;
	private String pmpushSampleMan;
	
	public AfElement() {}
	
	public AfElement(Long afId, String EType, Integer EAmount, Double EPs, String EMachine, String EFormat, String EColorFront, String EColorBack, Integer EColorFrontN, Integer EColorBackN,
			String EPaper, String EPaperFrom, String ESs, Double EReam, Double EOvers, String EPlateType, Integer EPlateAmount, Date EPlanPm, Date EPlanBp, Date EPlanProof, Date EPlanPress,
			String EIdePm, String EIdeBp, String EIdeProof, String EIdePress, Date EComPm, Date EComBp, Date EComProof, Date EComPress, Integer EP, Integer paperStatus, String paperSupplyMan,
			String paperGetMan, Date paperSupplyTime, Integer filmPlace, Date pmstartTime, String pmbindMan, Integer pmfilmCheck, String pmfilmStatus, String pmsaiMethod, String pmsaiMan,
			Integer pmoldPs, Integer pmnewPs, Double pmsaiLong, Double pmsaiMpa, Date pmpushSampleTime, String pmpushSampleMan) {
		this.afId = afId;
		this.EType = EType;
		this.EAmount = EAmount;
		this.EPs = EPs;
		this.EMachine = EMachine;
		this.EFormat = EFormat;
		this.EColorFront = EColorFront;
		this.EColorBack = EColorBack;
		this.EColorFrontN = EColorFrontN;
		this.EColorBackN = EColorBackN;
		this.EPaper = EPaper;
		this.EPaperFrom = EPaperFrom;
		this.ESs = ESs;
		this.EReam = EReam;
		this.EOvers = EOvers;
		this.EPlateType = EPlateType;
		this.EPlateAmount = EPlateAmount;
		this.EPlanPm = EPlanPm;
		this.EPlanBp = EPlanBp;
		this.EPlanProof = EPlanProof;
		this.EPlanPress = EPlanPress;
		this.EIdePm = EIdePm;
		this.EIdeBp = EIdeBp;
		this.EIdeProof = EIdeProof;
		this.EIdePress = EIdePress;
		this.EComPm = EComPm;
		this.EComBp = EComBp;
		this.EComProof = EComProof;
		this.EComPress = EComPress;
		this.EP = EP;
		this.paperStatus = paperStatus;
		this.paperSupplyMan = paperSupplyMan;
		this.paperGetMan = paperGetMan;
		this.paperSupplyTime = paperSupplyTime;
		this.filmPlace = filmPlace;
		this.pmstartTime = pmstartTime;
		this.pmbindMan = pmbindMan;
		this.pmfilmCheck = pmfilmCheck;
		this.pmfilmStatus = pmfilmStatus;
		this.pmsaiMethod = pmsaiMethod;
		this.pmsaiMan = pmsaiMan;
		this.pmoldPs = pmoldPs;
		this.pmnewPs = pmnewPs;
		this.pmsaiLong = pmsaiLong;
		this.pmsaiMpa = pmsaiMpa;
		this.pmpushSampleTime = pmpushSampleTime;
		this.pmpushSampleMan = pmpushSampleMan;
	}
	
	public Long getAfEId() {
		return this.afEId;
	}
	
	public void setAfEId(Long afEId) {
		this.afEId = afEId;
	}
	
	public Long getAfId() {
		return this.afId;
	}
	
	public void setAfId(Long afId) {
		this.afId = afId;
	}
	
	public String getEType() {
		return this.EType;
	}
	
	public void setEType(String EType) {
		this.EType = EType;
	}
	
	public Integer getEAmount() {
		return this.EAmount;
	}
	
	public void setEAmount(Integer EAmount) {
		this.EAmount = EAmount;
	}
	
	public Double getEPs() {
		return this.EPs;
	}
	
	public void setEPs(Double EPs) {
		this.EPs = EPs;
	}
	
	public String getEMachine() {
		return this.EMachine;
	}
	
	public void setEMachine(String EMachine) {
		this.EMachine = EMachine;
	}
	
	public String getEFormat() {
		return this.EFormat;
	}
	
	public void setEFormat(String EFormat) {
		this.EFormat = EFormat;
	}
	
	public String getEColorFront() {
		return this.EColorFront;
	}
	
	public void setEColorFront(String EColorFront) {
		this.EColorFront = EColorFront;
	}
	
	public String getEColorBack() {
		return this.EColorBack;
	}
	
	public void setEColorBack(String EColorBack) {
		this.EColorBack = EColorBack;
	}
	
	public Integer getEColorFrontN() {
		return this.EColorFrontN;
	}
	
	public void setEColorFrontN(Integer EColorFrontN) {
		this.EColorFrontN = EColorFrontN;
	}
	
	public Integer getEColorBackN() {
		return this.EColorBackN;
	}
	
	public void setEColorBackN(Integer EColorBackN) {
		this.EColorBackN = EColorBackN;
	}
	
	public String getEPaper() {
		return this.EPaper;
	}
	
	public void setEPaper(String EPaper) {
		this.EPaper = EPaper;
	}
	
	public String getEPaperFrom() {
		return this.EPaperFrom;
	}
	
	public void setEPaperFrom(String EPaperFrom) {
		this.EPaperFrom = EPaperFrom;
	}
	
	public String getESs() {
		return this.ESs;
	}
	
	public void setESs(String ESs) {
		this.ESs = ESs;
	}
	
	public Double getEReam() {
		return this.EReam;
	}
	
	public void setEReam(Double EReam) {
		this.EReam = EReam;
	}
	
	public Double getEOvers() {
		return this.EOvers;
	}
	
	public void setEOvers(Double EOvers) {
		this.EOvers = EOvers;
	}
	
	public String getEPlateType() {
		return this.EPlateType;
	}
	
	public void setEPlateType(String EPlateType) {
		this.EPlateType = EPlateType;
	}
	
	public Integer getEPlateAmount() {
		return this.EPlateAmount;
	}
	
	public void setEPlateAmount(Integer EPlateAmount) {
		this.EPlateAmount = EPlateAmount;
	}
	
	public Date getEPlanPm() {
		return this.EPlanPm;
	}
	
	public void setEPlanPm(Date EPlanPm) {
		this.EPlanPm = EPlanPm;
	}
	
	public Date getEPlanBp() {
		return this.EPlanBp;
	}
	
	public void setEPlanBp(Date EPlanBp) {
		this.EPlanBp = EPlanBp;
	}
	
	public Date getEPlanProof() {
		return this.EPlanProof;
	}
	
	public void setEPlanProof(Date EPlanProof) {
		this.EPlanProof = EPlanProof;
	}
	
	public Date getEPlanPress() {
		return this.EPlanPress;
	}
	
	public void setEPlanPress(Date EPlanPress) {
		this.EPlanPress = EPlanPress;
	}
	
	public String getEIdePm() {
		return this.EIdePm;
	}
	
	public void setEIdePm(String EIdePm) {
		this.EIdePm = EIdePm;
	}
	
	public String getEIdeBp() {
		return this.EIdeBp;
	}
	
	public void setEIdeBp(String EIdeBp) {
		this.EIdeBp = EIdeBp;
	}
	
	public String getEIdeProof() {
		return this.EIdeProof;
	}
	
	public void setEIdeProof(String EIdeProof) {
		this.EIdeProof = EIdeProof;
	}
	
	public String getEIdePress() {
		return this.EIdePress;
	}
	
	public void setEIdePress(String EIdePress) {
		this.EIdePress = EIdePress;
	}
	
	public Date getEComPm() {
		return this.EComPm;
	}
	
	public void setEComPm(Date EComPm) {
		this.EComPm = EComPm;
	}
	
	public Date getEComBp() {
		return this.EComBp;
	}
	
	public void setEComBp(Date EComBp) {
		this.EComBp = EComBp;
	}
	
	public Date getEComProof() {
		return this.EComProof;
	}
	
	public void setEComProof(Date EComProof) {
		this.EComProof = EComProof;
	}
	
	public Date getEComPress() {
		return this.EComPress;
	}
	
	public void setEComPress(Date EComPress) {
		this.EComPress = EComPress;
	}
	
	public Integer getEP() {
		return this.EP;
	}
	
	public void setEP(Integer EP) {
		this.EP = EP;
	}
	
	public Integer getPaperStatus() {
		return this.paperStatus;
	}
	
	public void setPaperStatus(Integer paperStatus) {
		this.paperStatus = paperStatus;
	}
	
	public String getPaperSupplyMan() {
		return this.paperSupplyMan;
	}
	
	public void setPaperSupplyMan(String paperSupplyMan) {
		this.paperSupplyMan = paperSupplyMan;
	}
	
	public String getPaperGetMan() {
		return this.paperGetMan;
	}
	
	public void setPaperGetMan(String paperGetMan) {
		this.paperGetMan = paperGetMan;
	}
	
	public Date getPaperSupplyTime() {
		return this.paperSupplyTime;
	}
	
	public void setPaperSupplyTime(Date paperSupplyTime) {
		this.paperSupplyTime = paperSupplyTime;
	}
	
	public Integer getFilmPlace() {
		return this.filmPlace;
	}
	
	public void setFilmPlace(Integer filmPlace) {
		this.filmPlace = filmPlace;
	}
	
	public Date getPmstartTime() {
		return this.pmstartTime;
	}
	
	public void setPmstartTime(Date pmstartTime) {
		this.pmstartTime = pmstartTime;
	}
	
	public String getPmbindMan() {
		return this.pmbindMan;
	}
	
	public void setPmbindMan(String pmbindMan) {
		this.pmbindMan = pmbindMan;
	}
	
	public Integer getPmfilmCheck() {
		return this.pmfilmCheck;
	}
	
	public void setPmfilmCheck(Integer pmfilmCheck) {
		this.pmfilmCheck = pmfilmCheck;
	}
	
	public String getPmfilmStatus() {
		return this.pmfilmStatus;
	}
	
	public void setPmfilmStatus(String pmfilmStatus) {
		this.pmfilmStatus = pmfilmStatus;
	}
	
	public String getPmsaiMethod() {
		return this.pmsaiMethod;
	}
	
	public void setPmsaiMethod(String pmsaiMethod) {
		this.pmsaiMethod = pmsaiMethod;
	}
	
	public String getPmsaiMan() {
		return this.pmsaiMan;
	}
	
	public void setPmsaiMan(String pmsaiMan) {
		this.pmsaiMan = pmsaiMan;
	}
	
	public Integer getPmoldPs() {
		return this.pmoldPs;
	}
	
	public void setPmoldPs(Integer pmoldPs) {
		this.pmoldPs = pmoldPs;
	}
	
	public Integer getPmnewPs() {
		return this.pmnewPs;
	}
	
	public void setPmnewPs(Integer pmnewPs) {
		this.pmnewPs = pmnewPs;
	}
	
	public Double getPmsaiLong() {
		return this.pmsaiLong;
	}
	
	public void setPmsaiLong(Double pmsaiLong) {
		this.pmsaiLong = pmsaiLong;
	}
	
	public Double getPmsaiMpa() {
		return this.pmsaiMpa;
	}
	
	public void setPmsaiMpa(Double pmsaiMpa) {
		this.pmsaiMpa = pmsaiMpa;
	}
	
	public Date getPmpushSampleTime() {
		return this.pmpushSampleTime;
	}
	
	public void setPmpushSampleTime(Date pmpushSampleTime) {
		this.pmpushSampleTime = pmpushSampleTime;
	}
	
	public String getPmpushSampleMan() {
		return this.pmpushSampleMan;
	}
	
	public void setPmpushSampleMan(String pmpushSampleMan) {
		this.pmpushSampleMan = pmpushSampleMan;
	}
}
