Ext.ns('org','org.kyerp');
Ext.ns('org.kyerp.security');
Ext.ns('org.kyerp.org');
Ext.ns('org.kyerp.warehouse');
Ext.ns('org.kyerp.crm');

/** ***************************************************************************** */
/** 人力资源管理模块 */
/** ***************************************************************************** */
org.kyerp.security.UserPanel_STORE_URL = "security/User/jsonList.html";
/** ***************************************************************************** */
org.kyerp.org.Employee_TREE_URL = "org/Employee/jsonTree.html";
org.kyerp.org.EmployeePanel_STORE_URL = "org/Employee/jsonList.html";
org.kyerp.org.EmployeePanel_SAVE_URL = "org/Employee/jsonSave.html";
org.kyerp.org.EmployeePanel_DELETE_URL = "org/Employee/jsonDelete.html";
/** ***************************************************************************** */
org.kyerp.org.DepartmentPanel_TREE_URL = "org/Department/jsonTree.html";
org.kyerp.org.DepartmentPanel_LIST_URL = "org/Department/jsonList.html";
org.kyerp.org.DepartmentPanel_SAVE_URL = "org/Department/jsonSave.html";
org.kyerp.org.DepartmentPanel_DELETE_URL = "org/Department/jsonDelete.html";
/** ***************************************************************************** */

/** ***************************************************************************** */
/** 库存管理模块 */
/** ***************************************************************************** */
org.kyerp.warehouse.BaseCategoryPanel_TREE_URL = "warehouse/BaseCategory/jsonTree.html";
org.kyerp.warehouse.BaseCategoryPanel_LIST_URL = "warehouse/BaseCategory/jsonList.html";
org.kyerp.warehouse.BaseCategoryPanel_SAVE_URL = "warehouse/BaseCategory/jsonSave.html";
org.kyerp.warehouse.BaseCategoryPanel_DELETE_URL = "warehouse/BaseCategory/jsonDelete.html";
/** ***************************************************************************** */
org.kyerp.warehouse.BrandPanel_TREE_URL = "warehouse/Brand/jsonTree.html";
org.kyerp.warehouse.BrandPanel_LIST_URL = "warehouse/Brand/jsonList.html";
org.kyerp.warehouse.BrandPanel_SAVE_URL = "warehouse/Brand/jsonSave.html";
org.kyerp.warehouse.BrandPanel_DELETE_URL = "warehouse/Brand/jsonDelete.html";
/** ***************************************************************************** */
org.kyerp.warehouse.UnitPanel_TREE_URL = "warehouse/Unit/jsonTree.html";
org.kyerp.warehouse.UnitPanel_LIST_URL = "warehouse/Unit/jsonList.html";
org.kyerp.warehouse.UnitPanel_SAVE_URL = "warehouse/Unit/jsonSave.html";
org.kyerp.warehouse.UnitPanel_DELETE_URL = "warehouse/Unit/jsonDelete.html";
/** ***************************************************************************** */
org.kyerp.warehouse.EnteringMaterialPanel_STORE_URL = "warehouse/EnteringMaterial/jsonList.html";
org.kyerp.warehouse.EnteringMaterialPanel_SAVE_URL = "warehouse/EnteringMaterial/jsonSave.html";
org.kyerp.warehouse.EnteringMaterialPanel_DELETE_URL = "warehouse/EnteringMaterial/jsonDelete.html";
/** ***************************************************************************** */
org.kyerp.warehouse.MaterialCategoryPanel_TREE_URL = "warehouse/MaterialCategory/jsonTree.html";
org.kyerp.warehouse.MaterialCategoryPanel_LIST_URL = "warehouse/MaterialCategory/jsonList.html";
org.kyerp.warehouse.MaterialCategoryPanel_SAVE_URL = "warehouse/MaterialCategory/jsonSave.html";
org.kyerp.warehouse.MaterialCategoryPanel_DELETE_URL = "warehouse/MaterialCategory/jsonDelete.html";
/** ***************************************************************************** */
org.kyerp.warehouse.MaterialListPanel_STORE_URL = "warehouse/Material/jsonList.html";
org.kyerp.warehouse.MaterialListPanel_SAVE_URL = "warehouse/Material/jsonSave.html";
org.kyerp.warehouse.MaterialListPanel_DELETE_URL = "warehouse/Material/jsonDelete.html";
/** ***************************************************************************** */
org.kyerp.warehouse.PaperOfMaterialPanel_STORE_URL = "warehouse/PaperOfMaterial/jsonList.html";
org.kyerp.warehouse.PaperOfMaterialPanel_SAVE_URL = "warehouse/PaperOfMaterial/jsonSave.html";
org.kyerp.warehouse.PaperOfMaterialPanel_DELETE_URL = "warehouse/PaperOfMaterial/jsonDelete.html";
/** ***************************************************************************** */
org.kyerp.warehouse.MaterialPanel_STORE_URL = "warehouse/Material/jsonList.html";
/** ***************************************************************************** */
org.kyerp.warehouse.Supplier_TREE_URL = "warehouse/Supplier/jsonTree.html";
org.kyerp.warehouse.SupplierPanel_STORE_URL = "warehouse/Supplier/jsonList.html";
org.kyerp.warehouse.SupplierPanel_SAVE_URL = "warehouse/Supplier/jsonSave.html";
org.kyerp.warehouse.SupplierPanel_DELETE_URL = "warehouse/Supplier/jsonDelete.html";
/** ***************************************************************************** */
org.kyerp.warehouse.InOutTypePanel_TREE_URL = "warehouse/InOutType/jsonTree.html";
org.kyerp.warehouse.InOutTypePanel_LIST_URL = "warehouse/InOutType/jsonList.html";
org.kyerp.warehouse.InOutTypePanel_SAVE_URL = "warehouse/InOutType/jsonSave.html";
org.kyerp.warehouse.InOutTypePanel_DELETE_URL = "warehouse/InOutType/jsonDelete.html";
/** ***************************************************************************** */
org.kyerp.warehouse.SupplierTypePanel_TREE_URL = "warehouse/SupplierType/jsonTree.html";
org.kyerp.warehouse.SupplierTypePanel_LIST_URL = "warehouse/SupplierType/jsonList.html";
org.kyerp.warehouse.SupplierTypePanel_SAVE_URL = "warehouse/SupplierType/jsonSave.html";
org.kyerp.warehouse.SupplierTypePanel_DELETE_URL = "warehouse/SupplierType/jsonDelete.html";
/** ***************************************************************************** */
org.kyerp.warehouse.Warehouse_ALL_LIST_URL = "warehouse/Warehouse/jsonAllList.html";
org.kyerp.warehouse.WarehousePanel_TREE_URL = "warehouse/Warehouse/jsonTree.html";
org.kyerp.warehouse.WarehousePanel_LIST_URL = "warehouse/Warehouse/jsonList.html";
org.kyerp.warehouse.WarehousePanel_SAVE_URL = "warehouse/Warehouse/jsonSave.html";
org.kyerp.warehouse.WarehousePanel_DELETE_URL = "warehouse/Warehouse/jsonDelete.html";
/** ***************************************************************************** */
org.kyerp.warehouse.PurchaseOrderPanel_STORE_URL = "warehouse/PurchaseOrder/jsonList.html";
org.kyerp.warehouse.PurchaseOrderPanel_SAVE_URL = "warehouse/PurchaseOrder/jsonSave.html";
org.kyerp.warehouse.PurchaseOrderPanel_DELETE_URL = "warehouse/PurchaseOrder/jsonDelete.html";
org.kyerp.warehouse.PurchaseOrderDetail_DELETE_URL = "warehouse/PurchaseOrderDetail/jsonDelete.html";
org.kyerp.warehouse.PurchaseOrder_PostForCheck_URL = "warehouse/PurchaseOrder/jsonPostForCheck.html";
org.kyerp.warehouse.PurchaseOrder_ReturnForEdit_URL = "warehouse/PurchaseOrder/jsonReturnForEdit.html";
org.kyerp.warehouse.PurchaseOrder_CheckBill_URL = "warehouse/PurchaseOrder/jsonCheckBill.html";
/** ***************************************************************************** */
org.kyerp.warehouse.StockListPanel_STORE_URL = "warehouse/Stock/jsonList.html";
/** ***************************************************************************** */
org.kyerp.warehouse.StockDetail_URL = "warehouse/StockDetail/jsonList.html";
/** ***************************************************************************** */
org.kyerp.warehouse.InStockPanel_STORE_URL = "warehouse/InStock/jsonList.html";
org.kyerp.warehouse.InStockPanel_SAVE_URL = "warehouse/InStock/jsonSave.html";
org.kyerp.warehouse.InStockPanel_DELETE_URL = "warehouse/InStock/jsonDelete.html";
org.kyerp.warehouse.InStockDetail_DELETE_URL = "warehouse/InStockDetail/jsonDelete.html";
org.kyerp.warehouse.InStock_PostForCheck_URL = "warehouse/InStock/jsonPostForCheck.html";
org.kyerp.warehouse.InStock_ReturnForEdit_URL = "warehouse/InStock/jsonReturnForEdit.html";
org.kyerp.warehouse.InStock_CheckBill_URL = "warehouse/InStock/jsonCheckBill.html";
/** ***************************************************************************** */
org.kyerp.warehouse.OutStockPanel_STORE_URL = "warehouse/OutStock/jsonList.html";
org.kyerp.warehouse.OutStockPanel_SAVE_URL = "warehouse/OutStock/jsonSave.html";
org.kyerp.warehouse.OutStockPanel_DELETE_URL = "warehouse/OutStock/jsonDelete.html";
org.kyerp.warehouse.OutStockDetail_DELETE_URL = "warehouse/OutStockDetail/jsonDelete.html";
org.kyerp.warehouse.OutStock_PostForCheck_URL = "warehouse/OutStock/jsonPostForCheck.html";
org.kyerp.warehouse.OutStock_ReturnForEdit_URL = "warehouse/OutStock/jsonReturnForEdit.html";
org.kyerp.warehouse.OutStock_CheckBill_URL = "warehouse/OutStock/jsonCheckBill.html";
/** ***************************************************************************** */

/** ***************************************************************************** */
/** 客户管理模块 */
/** ***************************************************************************** */
org.kyerp.crm.ClientTypePanel_TREE_URL = "crm/ClientType/jsonTree.html";
org.kyerp.crm.ClientTypePanel_LIST_URL = "crm/ClientType/jsonList.html";
org.kyerp.crm.ClientTypePanel_SAVE_URL = "crm/ClientType/jsonSave.html";
org.kyerp.crm.ClientTypePanel_DELETE_URL = "crm/ClientType/jsonDelete.html";
/** ***************************************************************************** */
org.kyerp.crm.ClientPanel_STORE_URL = "crm/Client/jsonList.html";
org.kyerp.crm.ClientPanel_SAVE_URL = "crm/Client/jsonSave.html";
org.kyerp.crm.ClientPanel_DELETE_URL = "crm/Client/jsonDelete.html";
/** ***************************************************************************** */