package com.tyopf.vo;
// default package
// Generated 2008-7-23 17:16:56 by Hibernate Tools 3.2.0.beta8

/**
 * AfMonthAfnoRange generated by hbm2java
 */
public class AfMonthAfnoRange implements java.io.Serializable {

	// Fields    

	private int monthNo;
	private Integer startSkafno;
	private Integer endSkafno;
	private Integer startLhafno;
	private Integer endLhafno;

	// Constructors

	/** default constructor */
	public AfMonthAfnoRange() {
	}

	/** minimal constructor */
	public AfMonthAfnoRange(int monthNo) {
		this.monthNo = monthNo;
	}

	/** full constructor */
	public AfMonthAfnoRange(int monthNo, Integer startSkafno,
			Integer endSkafno, Integer startLhafno, Integer endLhafno) {
		this.monthNo = monthNo;
		this.startSkafno = startSkafno;
		this.endSkafno = endSkafno;
		this.startLhafno = startLhafno;
		this.endLhafno = endLhafno;
	}

	// Property accessors
	public int getMonthNo() {
		return this.monthNo;
	}

	public void setMonthNo(int monthNo) {
		this.monthNo = monthNo;
	}

	public Integer getStartSkafno() {
		return this.startSkafno;
	}

	public void setStartSkafno(Integer startSkafno) {
		this.startSkafno = startSkafno;
	}

	public Integer getEndSkafno() {
		return this.endSkafno;
	}

	public void setEndSkafno(Integer endSkafno) {
		this.endSkafno = endSkafno;
	}

	public Integer getStartLhafno() {
		return this.startLhafno;
	}

	public void setStartLhafno(Integer startLhafno) {
		this.startLhafno = startLhafno;
	}

	public Integer getEndLhafno() {
		return this.endLhafno;
	}

	public void setEndLhafno(Integer endLhafno) {
		this.endLhafno = endLhafno;
	}

}
